### ISSUE TITLE
Map Doesn't Update When Die 

### ISSUE THREAD

**Issue by DanSpedey** [SydMontague/ServerMinimap#1]
The map does not update if you die, it shows your death location - unless you leave and rejoin.

**Comment by DanSpedey** [comment]
@SydMontague Any update on this please?

**Comment by SydMontague** [comment]
Sorry, it looks like this is actually a problem within Minecraft/CraftBukkit.

When I reproduce the error the rendering and sending code of my plugin runs as intended, so there is actually no reason why the map is not updating anymore, except a bug somewhere else. :(

**Comment by DanSpedey** [comment]
So there is no way to fix this then?

**Comment by SydMontague** [comment]
Unfortunatly yes. 

The best thing you can do is upvoting [this](https://bugs.mojang.com/browse/MC-46345) bugreport, which seems to be directly related to the problem with my problem. :(

**Comment by SydMontague** [comment]
Seems like Mojang has fixed the issue in the meanwhile, so I'll close this one.
